[workspace]
members = ["reloader", "objparse"]
resolver = "3"

[workspace.dependencies]
object = { version = "0.36.7", default-features = false, features = [
    "read",
    "pe",
] }
thiserror = "2.0.12"
pelite = { version = "0.10.0", default-features = false }
windows-core = "0.61.0"
phnt = { version = "0.1.2", features = ["regenerate"] }

[workspace.dependencies.windows-sys]
version = "0.59.0"
features = [
    "Win32_Foundation",
    "Win32_System_Memory",
    "Win32_System_SystemServices",
    "Win32_System_Kernel",
    "Win32_System_Threading",
]
